services:
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 15
  # dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: dev
  #   container_name: server
  #   restart: always
  #   tty: true
  #   environment:
  #     - DATABASE_URL=${DOCKER_DATABASE_URL}
  #     - PORT=8080
  #   env_file:
  #     - .env
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - ./:/app/
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   links:
  #     - database
volumes:
  database-data:
