name: Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm run test
